apiVersion: v1
kind: Service
metadata:
  name: dj-service
  namespace: dev-dj
spec:
  selector:
    app: dev-dj   # Use the appropriate label to match your pod
  ports:
    - protocol: TCP
      port: 8000       # Port in the service
      targetPort: 8000 # Port in the pod
  type: NodePort
