apiVersion: v1
kind: Service
metadata:
  name: test2
  namespace: django
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080